######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 9 16:57:40 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
