######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 9 19:33:02 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mouse.h
SOURCES += main.cpp mouse.cpp
RESOURCES += mice.qrc
