######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 9 17:16:08 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mouse.h
SOURCES += main.cpp mouse.cpp
RESOURCES += mice.qrc
