######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 23 19:31:17 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += car.h carFrom.h carGenerator.h misc.h trafficLight.h
SOURCES += car.cpp carFrom.cpp carGenerator.cpp main.cpp
