######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 24 19:57:13 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += car.h carFrom.h carGenerator.h misc.h trafficLight.h
SOURCES += car.cpp carFrom.cpp carGenerator.cpp main.cpp trafficLight.cpp
