######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 21 22:01:17 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += car.h carGenerator.h misc.h trafficLight.h
SOURCES += car.cpp carGenerator.cpp main.cpp
