######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 2 11:30:12 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
