######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 9 10:05:12 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
