######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 2 18:37:54 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
